=== spryker/spryker-core/Bundles/Transfer/data/definition/transfer-01.xsd
<?xml version="1.0"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="spryker:transfer-01"
    targetNamespace="spryker:transfer-01"
    elementFormDefault="qualified">

    <xsd:element name="transfers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="transfer" maxOccurs="unbounded" minOccurs="0">
                    <xsd:complexType>

                        <xsd:sequence>
                            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                                <xsd:element name="property" maxOccurs="unbounded" minOccurs="0">
                                    <xsd:complexType mixed="true">
                                        <xsd:attribute type="xsd:string" name="name" use="required"/>
                                        <xsd:attribute type="xsd:string" name="type" use="required"/>
                                        <xsd:attribute type="xsd:string" name="singular" use="optional"/>
                                        <xsd:attribute type="xsd:string" name="description" use="optional"/>
                                        <xsd:attribute type="xsd:string" name="deprecated" use="optional"/>
                                        <xsd:attribute type="xsd:boolean" name="associative" use="optional"/>
                                        <xsd:attribute type="xsd:boolean" name="strict" use="optional"/>
                                        <xsd:attribute type="restParameterType" name="restRequestParameter" use="optional"/>
                                        <xsd:attribute type="restParameterType" name="restResponseParameter" use="optional"/>
                                        <xsd:attribute name="example" use="optional"/>
                                        <xsd:attribute name="examples" use="optional"/>
                                    </xsd:complexType>
                                </xsd:element>
                            </xsd:choice>
                        </xsd:sequence>

                        <xsd:attribute type="xsd:string" name="name" use="required"/>
                        <xsd:attribute type="xsd:string" name="deprecated" use="optional"/>
                        <xsd:attribute type="xsd:boolean" name="strict" use="optional"/>

                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="restParameterType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="yes"/>
            <xsd:enumeration value="no"/>
            <xsd:enumeration value="required"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== spryker/spryker-core/Bundles/AgentSecurityMerchantPortalGui/src/Spryker/Shared/AgentSecurityMerchantPortalGui/Transfer/agent_security_merchant_portal_gui.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="User">
        <property name="username" type="string"/>
        <property name="uuid" type="string" strict="true"/>
        <property name="password" type="string"/>
    </transfer>

    <transfer name="UserCollection" strict="true">
        <property name="users" type="User[]" singular="user"/>
    </transfer>

    <transfer name="UserCriteria">
        <property name="userConditions" type="UserConditions" strict="true"/>
    </transfer>

    <transfer name="UserConditions" strict="true">
        <property name="usernames" type="string[]" singular="username"/>
        <property name="statuses" type="string[]" singular="status"/>
        <property name="isMerchantAgent" type="bool"/>
    </transfer>

    <transfer name="Message">
        <property name="value" type="string"/>
    </transfer>

    <transfer name="MerchantUser">
        <property name="agentUsername" type="string"/>
        <property name="user" type="User"/>
    </transfer>

    <transfer name="MerchantUserCriteria">
        <property name="status" type="string"/>
        <property name="merchantStatus" type="string"/>
    </transfer>

    <transfer name="AuditLoggerConfigCriteria" strict="true">
        <property name="channelName" type="string"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/ContentProductAbstractListsRestApi/src/Spryker/Shared/ContentProductAbstractListsRestApi/Transfer/content_product_abstract_lists_rest_api.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="ContentProductAbstractListRestAttributes">
        <property name="abstractProducts" type="AbstractProductsRestAttributes[]"/>
    </transfer>

    <transfer name="AbstractProductsRestAttributes">
        <property name="sku" type="string"/>
    </transfer>

    <transfer name="ExecutedContentStorage">
        <property name="idContent" type="int" />
        <property name="type" type="string" />
        <property name="content" type="array" />
    </transfer>

    <transfer name="RestErrorMessage">
        <property name="status" type="int" />
        <property name="code" type="string" />
        <property name="detail" type="string" />
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/PriceProductSchedule/tests/_data/product_price_schedule.databuilder.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="PriceProductSchedule">
        <property name="priceProduct" type="PriceProduct"/>
    </transfer>

    <transfer name="PriceProductScheduleList">
        <property name="fkUser" type="int" dataBuilderRule="=1"/>
        <property name="isActive" type="bool" dataBuilderRule="=true"/>
        <property name="name" type="string" dataBuilderRule="unique()->sentence(5)"/>
    </transfer>

    <transfer name="PriceProduct">
        <property name="moneyValue" type="MoneyValue"/>
    </transfer>

    <transfer name="MoneyValue">
        <property name="netAmount" type="int" dataBuilderRule="numberBetween(1000, 10000)"/>
        <property name="grossAmount" type="int" dataBuilderRule="numberBetween(1000, 10000)"/>
    </transfer>

    <transfer name="PriceProductScheduleImport">
        <property name="netAmount" type="int" dataBuilderRule="numberBetween(1000, 10000)"/>
        <property name="grossAmount" type="int" dataBuilderRule="numberBetween(1000, 10000)"/>
    </transfer>
</transfers>

=== spryker/spryker-core/Bundles/Country/src/Spryker/Shared/Country/Transfer/country.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="Country">
        <property name="idCountry" type="int" />
        <property name="iso2Code" type="string" />
        <property name="iso3Code" type="string" />
        <property name="name" type="string" />
        <property name="postalCodeMandatory" type="bool" />
        <property name="postalCodeRegex" type="string" />
    </transfer>

    <transfer name="CountryCollection">
        <property name="countries" type="Country[]" />
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/PriceProductOfferVolume/src/Spryker/Shared/PriceProductOfferVolume/Transfer/price_product_offer_volume.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="PriceProductFilter">
        <property name="quantity" type="int"/>
    </transfer>

    <transfer name="PriceProduct">
        <property name="volumeQuantity" type="int"/>
        <property name="groupKey" type="string"/>
        <property name="isMergeable" type="bool"/>
        <property name="moneyValue" type="MoneyValue"/>
    </transfer>

    <transfer name="MoneyValue">
        <property name="priceData" type="string"/>
        <property name="grossAmount" type="int"/>
        <property name="netAmount" type="int"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/CmsBlockCategoryConnector/src/Spryker/Shared/CmsBlockCategoryConnector/Transfer/cms_block_category_connector.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="CmsBlock">
        <property name="idCmsBlock" type="int"/>
        <property name="idCategories" type="array"/>
    </transfer>

    <transfer name="Category">
        <property name="idCategory" type="int"/>
        <property name="idCmsBlocks" type="array"/>
    </transfer>

    <transfer name="CmsBlockCategoryPosition">
        <property name="idCmsBlockCategoryPosition" type="int"/>
        <property name="name" type="string"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/NavigationGui/src/Spryker/Shared/NavigationGui/Transfer/navigation_gui.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="Navigation">
        <property name="idNavigation" type="int"/>
        <property name="key" type="string"/>
        <property name="name" type="string"/>
        <property name="isActive" type="bool"/>
    </transfer>

    <transfer name="DuplicateNavigation">
        <property name="idBaseNavigation" type="int"/>
        <property name="key" type="string"/>
        <property name="name" type="string"/>
    </transfer>

    <transfer name="NavigationResponse">
        <property name="isSuccessful" type="bool"/>
        <property name="navigation" type="Navigation"/>
        <property name="errors" type="NavigationError[]" singular="error"/>
    </transfer>

    <transfer name="NavigationError">
        <property name="message" type="string"/>
    </transfer>

    <transfer name="NavigationNode">
        <property name="fkNavigation" type="int"/>
        <property name="fkParentNavigationNode" type="int"/>
        <property name="navigationNodeLocalizedAttributes" type="NavigationNodeLocalizedAttributes[]" singular="navigationNodeLocalizedAttribute"/>
        <property name="idNavigationNode" type="int"/>
        <property name="nodeType" type="string"/>
    </transfer>

    <transfer name="NavigationTree">
    </transfer>

    <transfer name="Url">
        <property name="url" type="string"/>
        <property name="fkLocale" type="int"/>
        <property name="fkResourceCategorynode" type="int"/>
        <property name="fkResourcePage" type="int"/>
        <property name="idUrl" type="int"/>
    </transfer>

    <transfer name="NavigationNodeLocalizedAttributes">
        <property name="fkLocale" type="int"/>
        <property name="fkUrl" type="int"/>
        <property name="cmsPageUrl" type="string"/>
        <property name="categoryUrl" type="string"/>
    </transfer>

    <transfer name="Locale">
        <property name="idLocale" type="int"/>
    </transfer>

    <transfer name="NavigationCriteria">
        <property name="idNavigation" type="int"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/CmsSlotBlockProductCategoryGui/src/Spryker/Shared/CmsSlotBlockProductCategoryGui/Transfer/cms_slot_block_product_category_gui.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="Locale">
        <property name="idLocale" type="int"/>
    </transfer>

    <transfer name="CmsSlotTemplateConfiguration">
        <property name="conditions" type="string[]" singular="condition"/>
    </transfer>

    <transfer name="CmsSlotBlockCondition">
        <property name="all" type="bool"/>
        <property name="productIds" type="int[]" singular="idProduct"/>
        <property name="categoryIds" type="int[]" singular="idCategory"/>
    </transfer>

    <transfer name="Pagination">
        <property name="page" type="int"/>
        <property name="lastPage" type="int"/>
        <property name="maxPerPage" type="int"/>
    </transfer>

    <transfer name="ProductAbstractSuggestionCollection">
        <property name="productAbstracts" type="ProductAbstract[]" singular="productAbstracts"/>
        <property name="pagination" type="Pagination"/>
    </transfer>

    <transfer name="CategoryCollection">
        <property name="categories" type="Category[]" singular="category"/>
    </transfer>

    <transfer name="Category">
        <property name="name" type="string"/>
        <property name="idCategory" type="int"/>
    </transfer>

    <transfer name="ProductAbstract">
    </transfer>
</transfers>
