=== spryker/spryker-core/Bundles/Transfer/data/definition/transfer-01.xsd
<?xml version="1.0"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="spryker:transfer-01"
    targetNamespace="spryker:transfer-01"
    elementFormDefault="qualified">

    <xsd:element name="transfers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="transfer" maxOccurs="unbounded" minOccurs="0">
                    <xsd:complexType>

                        <xsd:sequence>
                            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                                <xsd:element name="property" maxOccurs="unbounded" minOccurs="0">
                                    <xsd:complexType mixed="true">
                                        <xsd:attribute type="xsd:string" name="name" use="required"/>
                                        <xsd:attribute type="xsd:string" name="type" use="required"/>
                                        <xsd:attribute type="xsd:string" name="singular" use="optional"/>
                                        <xsd:attribute type="xsd:string" name="description" use="optional"/>
                                        <xsd:attribute type="xsd:string" name="deprecated" use="optional"/>
                                        <xsd:attribute type="xsd:boolean" name="associative" use="optional"/>
                                        <xsd:attribute type="xsd:boolean" name="strict" use="optional"/>
                                        <xsd:attribute type="restParameterType" name="restRequestParameter" use="optional"/>
                                        <xsd:attribute type="restParameterType" name="restResponseParameter" use="optional"/>
                                        <xsd:attribute name="example" use="optional"/>
                                        <xsd:attribute name="examples" use="optional"/>
                                    </xsd:complexType>
                                </xsd:element>
                            </xsd:choice>
                        </xsd:sequence>

                        <xsd:attribute type="xsd:string" name="name" use="required"/>
                        <xsd:attribute type="xsd:string" name="deprecated" use="optional"/>
                        <xsd:attribute type="xsd:boolean" name="strict" use="optional"/>

                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="restParameterType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="yes"/>
            <xsd:enumeration value="no"/>
            <xsd:enumeration value="required"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== spryker/spryker-core/Bundles/ProductReview/src/Spryker/Shared/ProductReview/Transfer/product_review.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="ProductReview">
        <property name="idProductReview" type="int"/>
        <property name="fkProductAbstract" type="int"/>
        <property name="fkLocale" type="int"/>
        <property name="customerReference" type="string"/>
        <property name="rating" type="int"/>
        <property name="summary" type="string"/>
        <property name="description" type="string"/>
        <property name="nickname" type="string"/>
        <property name="status" type="int"/>
        <property name="createdAt" type="string"/>
        <property name="updatedAt" type="string"/>
    </transfer>

    <transfer name="ProductReviewRequest">
        <property name="idProductAbstract" type="int"/>
        <property name="localeName" type="string"/>
        <property name="customerReference" type="string"/>
        <property name="rating" type="int"/>
        <property name="summary" type="string"/>
        <property name="description" type="string"/>
        <property name="nickname" type="string"/>
    </transfer>

    <transfer name="ProductReviewError">
        <property name="message" type="string"/>
    </transfer>

    <transfer name="ProductReviewResponse">
        <property name="productReview" type="ProductReview"/>
        <property name="isSuccess" type="bool"/>
        <property name="errors" type="ProductReviewError[]" singular="error"/>
    </transfer>

    <transfer name="ProductReviewSearchConfig">
        <property name="paginationConfig" type="PaginationConfig"/>
    </transfer>

    <transfer name="ProductReviewSearchRequest">
        <property name="idProductAbstract" type="int"/>
        <property name="requestParams" type="array"/>
    </transfer>

    <transfer name="ProductAbstractReview">
        <property name="idProductAbstract" type="int"/>
        <property name="averageRating" type="float"/>
        <property name="reviewCount" type="int"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/ProductAbstractDataFeed/src/Spryker/Shared/ProductAbstractDataFeed/Transfer/product_abstract_data_feed.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="ProductAbstractDataFeed">
        <property name="joinPrice" type="bool"/>
        <property name="joinCategory" type="bool"/>
        <property name="joinImage" type="bool"/>
        <property name="joinProduct" type="bool"/>
        <property name="joinOption" type="bool"/>
        <property name="useOnlyActiveStock" type="bool"/>
        <property name="updatedFrom" type="string"/>
        <property name="updatedTo" type="string"/>
        <property name="idLocale" type="int"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/SalesServicePoint/src/Spryker/Shared/SalesServicePoint/Transfer/sales_service_point.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="SalesOrderItemServicePoint" strict="true">
        <property name="idSalesOrderItemServicePoint" type="int"/>
        <property name="idSalesOrderItem" type="int"/>
        <property name="name" type="string"/>
        <property name="key" type="string"/>
    </transfer>

    <transfer name="Item">
        <property name="idSalesOrderItem" type="int"/>
        <property name="salesOrderItemServicePoint" type="SalesOrderItemServicePoint" strict="true"/>
        <property name="servicePoint" type="ServicePoint" strict="true"/>
    </transfer>

    <transfer name="SalesOrderItemServicePointCriteria" strict="true">
        <property name="salesOrderItemServicePointConditions" type="SalesOrderItemServicePointConditions"/>
    </transfer>

    <transfer name="SalesOrderItemServicePointConditions" strict="true">
        <property name="salesOrderItemIds" type="int[]" singular="salesOrderItemId"/>
    </transfer>

    <transfer name="SalesOrderItemServicePointCollection" strict="true">
        <property name="salesOrderItemServicePoints" type="SalesOrderItemServicePoint[]" singular="salesOrderItemServicePoint"/>
    </transfer>

    <transfer name="ServicePoint" strict="true">
        <property name="name" type="string"/>
        <property name="key" type="string"/>
    </transfer>

    <transfer name="Quote">
        <property name="items" type="Item[]" singular="item"/>
    </transfer>

    <transfer name="SaveOrder">
    </transfer>

    <transfer name="SalesOrderItemCollectionDeleteCriteria" strict="true">
        <property name="salesOrderItemIds" type="int[]" singular="idSalesOrderItem"/>
    </transfer>

    <transfer name="SalesOrderItemServicePointCollectionDeleteCriteria" strict="true">
        <property name="salesOrderItemIds" type="int[]" singular="idSalesOrderItem"/>
    </transfer>

    <transfer name="SalesOrderItemServicePointCollectionResponse" strict="true">
    </transfer>

    <transfer name="SalesOrderAmendmentItemCollection" strict="true">
        <property name="itemsToUpdate" type="Item[]" singular="itemToUpdate"/>
        <property name="itemsToSkip" type="Item[]" singular="itemToSkip"/>
    </transfer>

    <transfer name="Order">
        <property name="items" type="Item[]" singular="item"/>
    </transfer>

    <transfer name="SalesOrderItemCollectionResponse" strict="true">
        <property name="items" type="Item[]" singular="item"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/ProductOptionStorage/src/Spryker/Shared/ProductOptionStorage/Transfer/product_option_storage.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="ProductOptionValueStorage">
        <property name="idProductOptionValue" type="int"/>
        <property name="sku" type="string"/>
        <property name="price" type="int"/>
        <property name="prices" type="array" singular="prices"/>
        <property name="value" type="string"/>
    </transfer>

    <transfer name="ProductOptionGroupStorage">
        <property name="name" type="string"/>
        <property name="productOptionValues" singular="productOptionValue" type="ProductOptionValueStorage[]"/>
    </transfer>

    <transfer name="ProductAbstractOptionStorage">
        <property name="idProductAbstract" type="int"/>
        <property name="productOptionGroups" singular="productOptionGroup" type="ProductOptionGroupStorage[]"/>
    </transfer>

    <transfer name="ProductAbstractOptionGroupStatus">
        <property name="idProductAbstract" type="int"/>
        <property name="isActive" type="bool"/>
        <property name="productOptionGroupName" type="string"/>
    </transfer>

    <transfer name="Currency">
        <property name="code" type="string"/>
    </transfer>

    <transfer name="StorageProductOptionGroupCollection">
        <property name="productOptionGroups" type="StorageProductOptionGroup[]" singular="productOptionGroup"/>
    </transfer>

    <transfer name="SynchronizationData">
        <property name="store" type="string"/>
        <property name="reference" type="string"/>
    </transfer>

    <transfer name="Store">
        <property name="idStore" type="int"/>
        <property name="name" type="string"/>
    </transfer>

    <transfer name="ProductOptionValueStorePricesRequest">
        <property name="prices" type="MoneyValue[]" singular="price"/>
    </transfer>

    <transfer name="ProductOptionValueStorePricesResponse">
        <property name="storePrices" type="array" singular="storePrices"/>
    </transfer>

    <transfer name="MoneyValue">
        <property name="netAmount" type="int"/>
        <property name="grossAmount" type="int"/>
    </transfer>

    <transfer name="StorageProductOptionGroup">
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/CartCurrencyConnector/src/Spryker/Shared/CartCurrencyConnector/Transfer/cart_currency_connector.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="QuoteResponse">
        <property name="isSuccessful" type="bool"/>
    </transfer>

    <transfer name="Currency">
        <property name="code" type="string"/>
    </transfer>

    <transfer name="Quote">
        <property name="currency" type="Currency"/>
        <property name="items" type="Item[]" singular="item"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/ProductLabelSearch/src/Spryker/Shared/ProductLabelSearch/Transfer/product_label_search.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="Locale">
    </transfer>

    <transfer name="PageMap">
    </transfer>

    <transfer name="ProductPageLoad">
        <property name="productAbstractIds" type="array" singular="productAbstractIds"/>
        <property name="payloadTransfers" type="array" singular="payloadTransfers"/>
    </transfer>

    <transfer name="ProductPageSearch">
        <property name="labelIds" type="array" singular="labelIds"/>
        <property name="store" type="string"/>
    </transfer>

    <transfer name="ProductPayload">
        <property name="labelIds" type="array" singular="labelIds"/>
        <property name="idProductAbstract" type="int"/>
    </transfer>

    <transfer name="ProductLabel">
        <property name="storeRelation" type="StoreRelation"/>
        <property name="productLabelProductAbstracts" type="ProductLabelProductAbstract[]" singular="productLabelProductAbstract"/>
        <property name="idProductLabel" type="int"/>
        <property name="isExclusive" type="bool"/>
        <property name="position" type="int"/>
    </transfer>

    <transfer name="ProductLabelCriteria">
        <property name="productLabelConditions" type="ProductLabelConditions" strict="true"/>
        <property name="productAbstractIds" type="int[]" singular="productAbstractId" deprecated="Use ProductLabelConditions.productAbstractIds instead."/>
        <property name="pagination" type="Pagination" strict="true"/>
        <property name="sortCollection" type="Sort[]" singular="sort" strict="true"/>
        <property name="withProductLabelStores" type="bool"/>
        <property name="withProductLabelProductAbstracts" type="bool"/>
    </transfer>

    <transfer name="ProductLabelProductAbstract">
    </transfer>

    <transfer name="Store">
        <property name="name" type="string"/>
    </transfer>

    <transfer name="StoreRelation">
        <property name="stores" type="Store[]" singular="stores"/>
    </transfer>

    <transfer name="ProductLabelCollection" strict="true">
        <property name="productLabels" type="ProductLabel[]" singular="productLabel"/>
    </transfer>

    <transfer name="Pagination">
        <property name="offset" type="int"/>
        <property name="limit" type="int"/>
    </transfer>

    <transfer name="Sort">
        <property name="field" type="string"/>
        <property name="isAscending" type="bool"/>
    </transfer>

    <transfer name="ProductLabelConditions" strict="true">
        <property name="productAbstractIds" type="int[]" singular="productAbstractId"/>
        <property name="isActive" type="bool"/>
    </transfer>

    <transfer name="HydrateEventsRequest">
        <property name="eventEntities" type="EventEntity[]" singular="eventEntity" description="Collection of event entities to be processed"/>
        <property name="foreignKeyName" type="string" description="Name of the foreign key field used for grouping or identification"/>
    </transfer>

    <transfer name="HydrateEventsResponse">
        <property name="idTimestampMap" type="array" associative="true" singular="id" description="Map of event entity IDs to their corresponding timestamps"/>
        <property name="foreignKeyTimestampMap" type="array" associative="true" singular="foreignKey" description="Map of foreign key values to their corresponding timestamps"/>
    </transfer>

    <transfer name="EventEntity">
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/KernelApp/src/Spryker/Shared/KernelApp/Transfer/kernel_app.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="spryker:transfer-01
    http://static.spryker.com/transfer-01.xsd">

    <transfer name="AppConfigUpdated" strict="true">
        <property name="status" type="string" description="The Status of an App that enabled (NEW) or disabled (CONNECTED)"/>
        <property name="isActive" type="bool"/>
        <property name="config" type="array" singular="config"/>
        <property name="appIdentifier" type="string" description="The identifier of an App"/>
        <property name="messageChannels" type="array" singular="messageChannel" description="The message channels that are used by an App"/>
        <property name="messageAttributes" type="MessageAttributes"/>
    </transfer>

    <transfer name="AppConfig" strict="true">
        <property name="appIdentifier" type="string" description="The identifier of an App"/>
        <property name="messageChannels" type="array" singular="messageChannel" description="The message channels that are used by an App"/>
        <property name="status" type="string"/>
        <property name="isActive" type="bool"/>
        <property name="config" type="array" singular="config"/>
    </transfer>

    <transfer name="AcpHttpRequest" strict="true">
        <property name="method" type="string"/>
        <property name="uri" type="string"/>
        <property name="headers" type="array" associative="true" singular="header"/>
        <property name="query" type="array" associative="true" singular="param"/>
        <property name="body" type="string"/>
    </transfer>

    <transfer name="AcpHttpResponse" strict="true">
        <property name="httpStatusCode" type="int"/>
        <property name="content" type="string"/>
    </transfer>

    <transfer name="MessageAttributes">
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/OrderAmendmentsRestApi/src/Spryker/Shared/OrderAmendmentsRestApi/Transfer/order_amendments_rest_api.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="Quote">
        <property name="amendmentOrderReference" type="string" strict="true" description="A reference to an amended sales order."/>
    </transfer>

    <transfer name="RestCartsAttributes">
        <property name="amendmentOrderReference" type="string" strict="true" description="A reference to an amended sales order."/>
    </transfer>

    <transfer name="RestCartReorderRequestAttributes" strict="true">
        <property name="isAmendment" type="bool" restRequestParameter="yes" description="A flag indicating if an operation is an amendment."/>
    </transfer>

    <transfer name="CartReorderRequest" strict="true">
        <property name="isAmendment" type="bool" description="A flag indicating if an operation is an amendment."/>
    </transfer>

    <transfer name="RestOrderAmendmentsAttributes" strict="true">
        <property name="createdAt" type="string" description="The timestamp when an entity was created."/>
        <property name="updatedAt" type="string" description="The timestamp when an entity was last updated."/>
    </transfer>

    <transfer name="Order">
        <property name="salesOrderAmendment" type="SalesOrderAmendment" strict="true" description="An amendment to a sales order."/>
    </transfer>

    <transfer name="SalesOrderAmendment" strict="true">
        <property name="uuid" type="string" description="A Universally Unique Identifier for an entity."/>
        <property name="createdAt" type="string" description="The timestamp when an entity was created."/>
        <property name="updatedAt" type="string" description="The timestamp when an entity was last updated."/>
    </transfer>

</transfers>
