=== spryker/spryker-core/Bundles/Transfer/data/definition/transfer-01.xsd
<?xml version="1.0"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="spryker:transfer-01"
    targetNamespace="spryker:transfer-01"
    elementFormDefault="qualified">

    <xsd:element name="transfers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="transfer" maxOccurs="unbounded" minOccurs="0">
                    <xsd:complexType>

                        <xsd:sequence>
                            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                                <xsd:element name="property" maxOccurs="unbounded" minOccurs="0">
                                    <xsd:complexType mixed="true">
                                        <xsd:attribute type="xsd:string" name="name" use="required"/>
                                        <xsd:attribute type="xsd:string" name="type" use="required"/>
                                        <xsd:attribute type="xsd:string" name="singular" use="optional"/>
                                        <xsd:attribute type="xsd:string" name="description" use="optional"/>
                                        <xsd:attribute type="xsd:string" name="deprecated" use="optional"/>
                                        <xsd:attribute type="xsd:boolean" name="associative" use="optional"/>
                                        <xsd:attribute type="xsd:boolean" name="strict" use="optional"/>
                                        <xsd:attribute type="restParameterType" name="restRequestParameter" use="optional"/>
                                        <xsd:attribute type="restParameterType" name="restResponseParameter" use="optional"/>
                                        <xsd:attribute name="example" use="optional"/>
                                        <xsd:attribute name="examples" use="optional"/>
                                    </xsd:complexType>
                                </xsd:element>
                            </xsd:choice>
                        </xsd:sequence>

                        <xsd:attribute type="xsd:string" name="name" use="required"/>
                        <xsd:attribute type="xsd:string" name="deprecated" use="optional"/>
                        <xsd:attribute type="xsd:boolean" name="strict" use="optional"/>

                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="restParameterType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="yes"/>
            <xsd:enumeration value="no"/>
            <xsd:enumeration value="required"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== spryker/spryker-core/Bundles/Refund/src/Spryker/Shared/Refund/Transfer/refund.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="Refund">
        <property name="idRefund" type="int"/>
        <property name="fkSalesOrder" type="int"/>
        <property name="amount" type="int"/>
        <property name="comment" type="string"/>
        <property name="createdAt" type="string"/>
        <property name="items" singular="item" type="Item[]"/>
        <property name="expenses" singular="expense" type="Expense[]"/>
    </transfer>

    <transfer name="Item">
        <property name="idOrderItem" type="int"/>
        <property name="refundableAmount" type="int"/>
    </transfer>

    <transfer name="Expense">
        <property name="idExpense" type="int"/>
        <property name="refundableAmount" type="int"/>
    </transfer>

    <transfer name="Totals">
        <property name="refundTotal" type="int"/>
    </transfer>

    <transfer name="Order">
        <property name="currencyIsoCode" type="string"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/CmsContentWidget/src/Spryker/Shared/CmsContentWidget/Transfer/cms_content_widget.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="CmsContentWidgetConfigurationList">
        <property name="cmsContentWidgetConfigurationList" type="CmsContentWidgetConfiguration[]" singular="cmsContentWidgetConfiguration"/>
    </transfer>

    <transfer name="CmsContentWidgetConfiguration">
        <property name="templates" type="array" singular="template"/>
        <property name="usageInformation" type="string"/>
        <property name="functionName" type="string"/>
    </transfer>

    <transfer name="CmsContentWidgetFunctions">
        <property name="CmsContentWidgetFunctionList" type="CmsContentWidgetFunction[]" singular="cmsContentWidgetFunction"/>
    </transfer>

    <transfer name="CmsContentWidgetFunction">
        <property name="functionName" type="string"/>
        <property name="parameters" type="array" singular="parameter"/>
    </transfer>

    <transfer name="Locale">
        <property name="localeName" type="string"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/ProductOption/src/Spryker/Shared/ProductOption/Transfer/product_option.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="ProductOption">
        <property name="idSalesOrderItemOption" type="int" />
        <property name="idOptionValueUsage" type="int" />
        <property name="localeCode" type="string " />
        <property name="labelOptionType" type="string" />
        <property name="labelOptionValue" type="string" />
        <property name="taxRate" type="float" />
        <property name="calculatedDiscounts" type="CalculatedDiscount[]" singular="calculatedDiscount" />
        <property name="unitGrossPrice" type="int" />
        <property name="sumGrossPrice" type="int" />
        <property name="quantity" type="int" />
        <property name="refundableAmount" type="int"/>
        <property name="unitTaxAmount" type="int" />
        <property name="sumTaxAmount" type="int" />
    </transfer>

    <transfer name="ProductOptionsNameValue">
        <property name="type" type="string" />
        <property name="value" type="string" />
    </transfer>

    <transfer name="Item">
        <property name="idProductAbstract" type="int" />
        <property name="IdSalesOrderItem" type="int" />
        <property name="name" type="string" />
        <property name="unitGrossPrice" type="int" />
        <property name="quantity" type="int" />
        <property name="sumGrossPrice" type="int" />
        <property name="taxRate" type="float" />
        <property name="sku" type="string" />
        <property name="productOptions" type="ProductOption[]" singular="productOption" />
        <property name="unitGrossPriceWithProductOptions" type="int" />
        <property name="sumGrossPriceWithProductOptions" type="int" />
        <property name="refundableAmount" type="int"/>
        <property name="canceledAmount" type="int"/>
    </transfer>

    <transfer name="Quote">
        <property name="items" type="Item[]" singular="item"/>
        <property name="totals" type="Totals" />
        <property name="shippingAddress" type="Address"/>
    </transfer>

    <transfer name="Order">
        <property name="items" type="Item[]" singular="item"/>
        <property name="totals" type="Totals" />
        <property name="shippingAddress" type="Address"/>
    </transfer>

    <transfer name="Address">
        <property name="iso2Code" type="string" />
    </transfer>

    <transfer name="TaxTotal">
        <property name="amount" type="int" />
    </transfer>

    <transfer name="CheckoutResponse">
        <property name="isSuccess" type="bool" />
        <property name="errors" type="CheckoutError[]" singular="error" />
        <property name="isExternalRedirect" type="bool" />
        <property name="redirectUrl" type="string" />
        <property name="saveOrder" type="SaveOrder" />
    </transfer>

    <transfer name="SaveOrder">
        <property name="idSalesOrder" type="int" />
        <property name="orderItems" type="Item[]" singular="orderItem"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/QuickOrder/src/Spryker/Shared/QuickOrder/Transfer/quick_order.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="QuickOrder">
        <property name="items" type="QuickOrderItem[]"/>
    </transfer>

    <transfer name="QuickOrderItem">
        <property name="sku" type="string"/>
        <property name="productConcrete" type="ProductConcrete"/>
        <property name="quantity" type="int"/>
    </transfer>

    <transfer name="ProductConcrete">
        <property name="sku" type="string"/>
        <property name="idProductConcrete" type="int"/>
        <property name="fkProductAbstract" type="int"/>
    </transfer>

    <transfer name="Item">
        <property name="sku" type="string"/>
        <property name="id" type="int"/>
        <property name="idProductAbstract" type="int"/>
        <property name="quantity" type="int"/>
    </transfer>

    <transfer name="ItemValidation">
        <property name="item" type="Item"/>
        <property name="messages" type="Message[]" singular="Message"/>
        <property name="suggestedValues" type="Item"/>
    </transfer>

    <transfer name="Message">
        <property name="type" type="string"/>
        <property name="value" type="string"/>
        <property name="parameters" type="array"/>
    </transfer>
</transfers>

=== spryker/spryker-core/Bundles/QuoteApprovalShipmentConnector/src/Spryker/Shared/QuoteApprovalShipmentConnector/Transfer/quote_approval_shipment_connector.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="Quote">
        <property name="quoteApprovals" type="QuoteApproval[]" singular="quoteApproval"/>
        <property name="items" type="Item[]" singular="item"/>
        <property name="priceMode" type="string"/>
        <property name="shipment" type="Shipment" deprecated="Use item level shipment details (item.shipment) instead."/>
        <property name="shippingAddress" type="Address" deprecated="Use item level shipping addresses (item.shipment.shippingAddress) instead."/>
    </transfer>

    <transfer name="Item">
        <property name="shipment" type="Shipment"/>
    </transfer>

    <transfer name="Address">
    </transfer>

    <transfer name="Shipment">
        <property name="method" type="ShipmentMethod"/>
        <property name="shipmentSelection" type="string"/>
    </transfer>

    <transfer name="ShipmentMethod">
        <property name="storeCurrencyPrice" type="int"/>
    </transfer>

    <transfer name="ShipmentGroup">
        <property name="storeCurrencyPrice" type="int"/>
        <property name="shipment" type="Shipment"/>
    </transfer>

    <transfer name="Expense">
        <property name="storeCurrencyPrice" type="int"/>
        <property name="type" type="string"/>
        <property name="shipment" type="Shipment"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/Offer/src/Spryker/Shared/Offer/Transfer/offer.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="Quote">
        <property name="idOffer" type="int" description="Indicates an offer id, when it's a source of an order"/>
        <property name="offerFee" type="int"/>
        <property name="incomingItems" type="Item[]" singular="incomingItem"/>
        <property name="voucherDiscounts" type="Discount[]"/>
        <property name="priceMode" type="string"/>
        <property name="checkoutConfirmed" type="bool"/>
        <property name="items" type="Item[]" singular="item"/>
        <property name="customer" type="Customer"/>
    </transfer>

    <transfer name="Item">
        <property name="unitGrossPrice" type="int"/>
        <property name="unitNetPrice" type="int"/>

        <property name="sourceUnitGrossPrice" type="int"/>
        <property name="sourceUnitNetPrice" type="int"/>

        <property name="offerDiscount" type="int"/>
        <property name="offerFee" type="int"/>
        <property name="stock" type="int"/>
        <property name="savingAmount" type="int"/>
        <property name="originUnitGrossPrice" type="int"/>
        <property name="originUnitNetPrice" type="int"/>
        <property name="unitSubtotalAggregation" type="int"/>
        <property name="sumSubtotalAggregation" type="int"/>
        <property name="sku" type="string"/>
        <property name="quantity" type="int"/>
    </transfer>

    <transfer name="OfferList">
        <property name="customerReference" type="string"/>
        <property name="filter" type="Filter"/>
        <property name="offers" type="Offer[]" singular="offer"/>
        <property name="pagination" type="Pagination"/>
    </transfer>

    <transfer name="Offer">
        <property name="idOffer" type="int"/>
        <property name="quote" type="Quote"/>
        <property name="status" type="string"/>
        <property name="user" type="User"/>
        <property name="customerReference"  type="string"/>
        <property name="customer" type="Customer"/>
        <property name="createdAt" type="string"/>
        <property name="contactPerson" type="string"/>
        <property name="contactDate" type="string"/>
        <property name="note" type="string"/>
    </transfer>

    <transfer name="ResponseMessage">
        <property name="text" type="string"/>
    </transfer>

    <transfer name="OfferResponse">
        <property name="isSuccessful" type="bool"/>
        <property name="messages" type="ResponseMessage[]" singular="message"/>
        <property name="offer" type="Offer"/>
    </transfer>

    <transfer name="CalculableObject">
        <property name="totals" type="Totals"/>
        <property name="originalQuote" type="Quote"/>
        <property name="items" type="Item[]" singular="item"/>
    </transfer>

    <transfer name="Discount">
        <property name="voucherCode" type="string"/>
    </transfer>

    <transfer name="Totals">
        <property name="grandTotal" type="int"/>
    </transfer>

    <transfer name="CartChange">
        <property name="quote" type="Quote"/>
        <property name="items" type="Item[]" singular="item"/>
    </transfer>

    <transfer name="Pagination">
        <property name="page" type="int"/>
        <property name="maxPerPage" type="int"/>
        <property name="nbResults" type="int"/>
        <property name="firstIndex" type="int"/>
        <property name="lastIndex" type="int"/>
        <property name="firstPage" type="int"/>
        <property name="lastPage" type="int"/>
        <property name="nextPage" type="int"/>
        <property name="previousPage" type="int"/>
    </transfer>
</transfers>

=== spryker/spryker-core/Bundles/Category/tests/_data/category.databuilder.xml
<?xml version="1.0"?>
<transfers
        xmlns="spryker:transfer-01"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd"
>

    <transfer name="Category">
        <property name="idCategory" dataBuilderRule="="/>
        <property name="categoryKey" dataBuilderRule="unique()->sentence(2)"/>
        <property name="isActive" dataBuilderRule="boolean(100)"/>
        <property name="isInMenu" dataBuilderRule="boolean(100)"/>
        <property name="isClickable" dataBuilderRule="boolean(100)"/>
        <property name="isSearchable" dataBuilderRule="boolean(100)"/>
        <property name="name" dataBuilderRule="unique()->sentence(2)"/>
        <property name="url" dataBuilderRule="unique()->sentence(2)"/>
        <property name="imageName" dataBuilderRule="unique()->sentence(2)"/>
        <property name="categoryImageName" dataBuilderRule="unique()->sentence(2)"/>
        <property name="metaTitle" dataBuilderRule="unique()->sentence(2)"/>
        <property name="metaDescription" dataBuilderRule="unique()->sentence(2)"/>
        <property name="metaKeywords" dataBuilderRule="unique()->sentence(2)"/>
        <property name="fkCategoryTemplate" dataBuilderRule="="/>
    </transfer>

    <transfer name="Node">
        <property name="isRoot" dataBuilderRule="boolean(0)"/>
        <property name="isMain" dataBuilderRule="boolean(100)"/>
        <property name="nodeOrder" dataBuilderRule="randomDigit"/>
        <property name="name" dataBuilderRule="unique()->sentence(2)"/>
        <property name="path" dataBuilderRule="unique()->sentence(2)"/>
    </transfer>

    <transfer name="CategoryLocalizedAttributes">
        <property name="url" dataBuilderRule="unique()->sentence(2)"/>
        <property name="name" dataBuilderRule="unique()->sentence(2)"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/DataImport/src/Spryker/Shared/DataImport/Transfer/data-import.transfer.xml
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="DataImporterConfiguration">
        <property name="importType" type="string" />
        <property name="readerConfiguration" type="DataImporterReaderConfiguration" />
        <property name="throwException" type="bool" />
    </transfer>

    <transfer name="DataImporterReaderConfiguration">
        <property name="fileName" type="string" />
        <property name="fileEncoding" type="string" />
        <property name="directories" type="array" singular="directory" />
        <property name="offset" type="int" />
        <property name="limit" type="int" />
        <property name="csvDelimiter" type="string" />
        <property name="csvEnclosure" type="string" />
        <property name="csvEscape" type="string" />
        <property name="csvFlags" type="int" />
        <property name="csvHasHeader" type="bool" />
    </transfer>

    <transfer name="DataImporterReport">
        <property name="importType" type="string" />
        <property name="importTime" type="float" />
        <property name="importedDataSetCount" type="int" />
        <property name="expectedImportableDataSetCount" type="int" />
        <property name="isReaderCountable" type="bool" />
        <property name="isSuccess" type="bool" />
        <property name="dataImporterReports" type="DataImporterReport[]" singular="dataImporterReport" />
    </transfer>

</transfers>
