=== spryker/spryker-core/Bundles/Transfer/src/Spryker/Shared/Transfer/Definition/databuilder-01.xsd
<?xml version="1.0"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="spryker:databuilder-01"
    elementFormDefault="qualified">

    <xsd:element name="transfers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="transfer" maxOccurs="unbounded" minOccurs="0">
                    <xsd:complexType>

                        <xsd:sequence>
                            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                                <xsd:element name="property" maxOccurs="unbounded" minOccurs="0">
                                    <xsd:complexType mixed="true">
                                        <xsd:attribute type="xsd:string" name="name" use="required"/>
                                        <xsd:attribute type="xsd:string" name="type" use="optional"/>
                                        <xsd:attribute type="xsd:string" name="dataBuilderRule" use="optional"/>
                                        <xsd:attribute type="xsd:string" name="deprecated" use="optional"/>
                                    </xsd:complexType>
                                </xsd:element>
                            </xsd:choice>
                        </xsd:sequence>

                        <xsd:attribute type="xsd:string" name="name" use="required"/>
                        <xsd:attribute type="xsd:string" name="deprecated" use="optional"/>

                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== spryker/spryker-core/Bundles/Comment/tests/_data/comment.databuilder.xml
<?xml version="1.0"?>
<transfers
    xmlns="spryker:databuilder-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:databuilder-01 http://static.spryker.com/databuilder-01.xsd"
>

    <transfer name="CommentRequest">
        <property name="ownerId" dataBuilderRule="numberBetween(100, 9999)"/>
        <property name="ownerType" dataBuilderRule="unique()->word"/>
    </transfer>

    <transfer name="CommentFilter">
        <property name="ownerId" dataBuilderRule="numberBetween(100, 9999)"/>
        <property name="ownerType" dataBuilderRule="unique()->word"/>
    </transfer>

    <transfer name="Comment">
        <property name="message" dataBuilderRule="sentence(5)"/>
    </transfer>

    <transfer name="CommentTag">
        <property name="name" dataBuilderRule="unique()->word"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/Customer/tests/_data/customer.databuilder.xml
<?xml version="1.0"?>
<transfers
    xmlns="spryker:databuilder-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:databuilder-01 http://static.spryker.com/databuilder-01.xsd"
>

    <transfer name="Address">
        <property name="email" dataBuilderRule="email"/>
        <property name="salutation" dataBuilderRule="randomElement(['Mr', 'Mrs'])"/>
        <property name="firstName" dataBuilderRule="firstName"/>
        <property name="lastName" dataBuilderRule="lastName"/>
        <property name="address1" dataBuilderRule="address"/>
        <property name="company" dataBuilderRule="company"/>
        <property name="city" dataBuilderRule="city"/>
        <property name="zipCode" dataBuilderRule="postcode"/>
        <property name="phone" dataBuilderRule="e164PhoneNumber"/>
        <property name="state" dataBuilderRule="country"/>
        <property name="iso2Code" dataBuilderRule="=DE"/>
    </transfer>

    <transfer name="Customer">
        <property name="email" dataBuilderRule="email"/>
        <property name="firstName" dataBuilderRule="firstName"/>
        <property name="lastName" dataBuilderRule="lastName"/>
        <property name="company" dataBuilderRule="company"/>
        <property name="password" dataBuilderRule="password"/>
        <property name="gender" dataBuilderRule="randomElement(['Male', 'Female'])"/>
        <property name="dateOfBirth" dataBuilderRule="date('Y-m-d', '-20 years')"/>
        <property name="salutation" dataBuilderRule="randomElement(['Mr', 'Mrs'])"/>
        <property name="isGuest" dataBuilderRule="=false"/>
        <property name="locale" dataBuilderRule="locale"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/OauthClient/tests/SprykerTest/Zed/OauthClient/_data/oauth_client.databuilder.xml
<?xml version="1.0"?>
<transfers
    xmlns="spryker:databuilder-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:databuilder-01 http://static.spryker.com/databuilder-01.xsd"
>

    <transfer name="AccessTokenRequest">
        <property name="grantType" dataBuilderRule="=client_credentials"/>
        <property name="accessTokenRequestOptions" dataBuilderRule="AccessTokenRequestOptions"/>
        <property name="providerName" dataBuilderRule="=auth0"/>
        <property name="ignoreCache" dataBuilderRule="=false"/>
    </transfer>

    <transfer name="AccessTokenRequestOptions">
        <property name="audience" dataBuilderRule="=test_audience"/>
        <property name="storeReference" dataBuilderRule="=test_store_reference"/>
    </transfer>

    <transfer name="AccessTokenResponse" strict="true">
        <property name="isSuccessful" dataBuilderRule="=true"/>
        <property name="accessTokenError" dataBuilderRule="AccessTokenError"/>
        <property name="accessToken" dataBuilderRule="word(20)"/>
        <property name="expiresAt" dataBuilderRule="numberBetween(100, 9999)"/>
    </transfer>

    <transfer name="AccessTokenError" strict="true">
        <property name="error" dataBuilderRule="word(10)"/>
        <property name="errorDescription" dataBuilderRule="word(20)"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/DataImportMerchant/tests/_data/data_import_merchant.databuilder.xml
<?xml version="1.0"?>
<transfers
    xmlns="spryker:databuilder-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:databuilder-01 http://static.spryker.com/databuilder-01.xsd"
>

    <transfer name="DataImportMerchantFile" strict="true">
        <property name="merchantReference" dataBuilderRule="unique()->regexify('MER-[A-Z0-9]{8}')"/>
        <property name="idUser" dataBuilderRule="numberBetween(1, 100)"/>
        <property name="importerType" dataBuilderRule="randomElement(['merchant-product'])"/>
        <property name="status" dataBuilderRule="randomElement(['pending', 'processing', 'completed', 'failed'])"/>
    </transfer>

    <transfer name="DataImportMerchantFileInfo" strict="true">
        <property name="uploadedUrl" dataBuilderRule="url()"/>
        <property
            name="fileSystemName"
            dataBuilderRule="unique()->regexify('[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}\.csv')"
        />
        <property name="originalFileName" dataBuilderRule="regexify('[a-z-]{5,15}\.csv')"/>
        <property name="contentType" dataBuilderRule="randomElement(['text/csv', 'application/csv', 'text/plain'])"/>
        <property name="size" dataBuilderRule="numberBetween(1024, 1048576)"/>
        <property name="realPath" dataBuilderRule="regexify('/tmp/[a-z0-9]{8}-[a-z0-9]{4}\.csv')"/>
        <property name="content" dataBuilderRule="text(200)"/>
    </transfer>

    <transfer name="DataImportMerchantFileResult" strict="true">
        <property name="processedEntitiesCount" dataBuilderRule="numberBetween(0, 1000)"/>
        <property name="failedEntitiesCount" dataBuilderRule="numberBetween(0, 50)"/>
        <property name="errors" dataBuilderRule="text(100)"/>
        <property name="startedAt" dataBuilderRule="dateTime()->format('Y-m-d H:i:s')"/>
        <property name="finishedAt" dataBuilderRule="dateTime()->format('Y-m-d H:i:s')"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/ProductBundleCartsRestApi/tests/_data/product_bundle_carts_rest_api.databuilder.xml
<?xml version="1.0"?>
<transfers
    xmlns="spryker:databuilder-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:databuilder-01 http://static.spryker.com/databuilder-01.xsd"
>

    <transfer name="Shipment">
        <property name="shipmentSelection" dataBuilderRule="unique()->isbn10()"/>
        <property name="requestedDeliveryDate" dataBuilderRule="lexify('??????????')"/>
    </transfer>

    <transfer name="Address">
        <property name="firstName" dataBuilderRule="firstName()"/>
        <property name="lastName" dataBuilderRule="lastName()"/>
        <property name="address1" dataBuilderRule="address()"/>
        <property name="company" dataBuilderRule="company()"/>
        <property name="city" dataBuilderRule="city()"/>
        <property name="zipCode" dataBuilderRule="postcode()"/>
        <property name="state" dataBuilderRule="country()"/>
        <property name="iso2Code" dataBuilderRule="=DE"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/Content/tests/_data/content.databuilder.xml
<?xml version="1.0"?>
<transfers
    xmlns="spryker:databuilder-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:databuilder-01 http://static.spryker.com/databuilder-01.xsd"
>

    <transfer name="Content">
        <property name="idContent" type="int"/>
        <property name="name" type="string" dataBuilderRule="unique()->sentence(5)"/>
        <property name="description" type="string" dataBuilderRule="unique()->sentence(5)"/>
        <property name="contentTermKey" type="string" dataBuilderRule="unique()->sentence(5)"/>
        <property name="contentTypeKey" type="string" dataBuilderRule="unique()->sentence(5)"/>
        <property name="localizedContents" type="LocalizedContent[]" singular="localizedContent"/>
    </transfer>

    <transfer name="LocalizedContent">
        <property name="idContentLocalized" type="int"/>
        <property name="localeName" type="string" dataBuilderRule="unique()->sentence(5)"/>
        <property name="fkLocale" type="int" dataBuilderRule="null"/>
        <property name="fkContent" type="int"/>
        <property name="parameters" type="string"/>
    </transfer>

</transfers>

=== spryker/spryker-core/Bundles/MerchantProfile/tests/_data/merchant_profile.databuilder.xml
<?xml version="1.0"?>
<transfers
    xmlns="spryker:databuilder-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:databuilder-01 http://static.spryker.com/databuilder-01.xsd"
>

    <transfer name="Merchant">
        <property name="merchantProfile" type="MerchantProfile"/>
    </transfer>

    <transfer name="MerchantProfile">
        <property name="contactPersonRole" dataBuilderRule="lexify('??????????')"/>
        <property name="contactPersonTitle" dataBuilderRule="=Mr"/>
        <property name="contactPersonFirstName" dataBuilderRule="firstName()"/>
        <property name="contactPersonLastName" dataBuilderRule="lastName()"/>
        <property name="contactPersonPhone" dataBuilderRule="lexify('??????????')"/>
        <property name="logoUrl" dataBuilderRule="lexify('??????????')"/>
        <property name="publicEmail" dataBuilderRule="email()"/>
        <property name="publicPhone" dataBuilderRule="lexify('??????????')"/>
        <property name="descriptionGlossaryKey" dataBuilderRule="lexify('??????????')"/>
        <property name="bannerUrlGlossaryKey" dataBuilderRule="lexify('??????????')"/>
        <property name="deliveryTimeGlossaryKey" dataBuilderRule="lexify('??????????')"/>
        <property name="termsConditionsGlossaryKey" dataBuilderRule="lexify('??????????')"/>
        <property name="cancellationPolicyGlossaryKey" dataBuilderRule="lexify('??????????')"/>
        <property name="imprintGlossaryKey" dataBuilderRule="lexify('??????????')"/>
        <property name="dataPrivacyGlossaryKey" dataBuilderRule="lexify('??????????')"/>
        <property name="fkMerchant" dataBuilderRule="randomNumber(5)"/>
        <property name="addressCollection" type="MerchantProfileAddress[]"/>
        <property name="merchantProfileLocalizedGlossaryAttributes" type="MerchantProfileLocalizedGlossaryAttributes[]"/>
    </transfer>

    <transfer name="MerchantProfileAddress">
        <property name="fkCountry" dataBuilderRule="=60"/>
        <property name="address1" dataBuilderRule="lexify('??????????')"/>
        <property name="address2" dataBuilderRule="lexify('??????????')"/>
        <property name="address3" dataBuilderRule="lexify('??????????')"/>
        <property name="city" dataBuilderRule="lexify('??????????')"/>
        <property name="zipCode" dataBuilderRule="lexify('??????????')"/>
        <property name="fkMerchantProfile" dataBuilderRule="="/>
    </transfer>

    <transfer name="MerchantProfileLocalizedGlossaryAttributes">
        <property name="locale" type="Locale"/>
        <property name="merchantProfileGlossaryAttributeValues" type="MerchantProfileGlossaryAttributeValues"/>
    </transfer>

    <transfer name="MerchantProfileGlossaryAttributeValues">
        <property name="descriptionGlossaryKey" dataBuilderRule="lexify('??????????')"/>
        <property name="bannerUrlGlossaryKey" dataBuilderRule="lexify('??????????')"/>
        <property name="deliveryTimeGlossaryKey" dataBuilderRule="lexify('??????????')"/>
        <property name="termsConditionsGlossaryKey" dataBuilderRule="lexify('??????????')"/>
        <property name="cancellationPolicyGlossaryKey" dataBuilderRule="lexify('??????????')"/>
        <property name="imprintGlossaryKey" dataBuilderRule="lexify('??????????')"/>
        <property name="dataPrivacyGlossaryKey" dataBuilderRule="lexify('??????????')"/>
    </transfer>

    <transfer name="Url">
        <property name="fkLocale" type="int" dataBuilderRule="=66"/>
        <property name="url" type="string" dataBuilderRule="url()"/>
    </transfer>

</transfers>
