=== spryker/spryker-core/Bundles/Oms/src/Spryker/Shared/Oms/Definition/oms-01.xsd
<?xml version="1.0"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="spryker:oms-01"
    attributeFormDefault="unqualified"
    elementFormDefault="qualified">

    <xsd:element name="statemachine" type="statemachineType"/>

    <xsd:complexType name="processType" mixed="true">
        <xsd:sequence>
            <xsd:element type="subprocessesType" name="subprocesses" minOccurs="0"/>
            <xsd:element type="statesType" name="states" minOccurs="0" />
            <xsd:element type="transitionsType" name="transitions" minOccurs="0"/>
            <xsd:element type="eventsType" name="events" minOccurs="0" />
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="name" use="optional"/>
        <xsd:attribute type="xsd:string" name="main" use="optional"/>
        <xsd:attribute type="xsd:string" name="file" use="optional"/>
        <xsd:attribute type="xsd:string" name="prefix" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="statesType">
        <xsd:sequence>
            <xsd:element type="stateType" name="state" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="transitionsType">
        <xsd:sequence>
            <xsd:element type="transitionType" name="transition" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="stateType" mixed="true">
        <xsd:sequence>
            <xsd:element name="flag" maxOccurs="unbounded" minOccurs="0">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="exclude from customer"/>
                        <xsd:enumeration value="exclude from invoice"/>
                        <xsd:enumeration value="ready for invoice"/>
                        <xsd:enumeration value="waiting for export"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="name" use="required"/>
        <xsd:attribute type="xsd:string" name="display" use="optional"/>
        <xsd:attribute type="xsd:string" name="reserved" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="statemachineType" mixed="true">
        <xsd:sequence>
            <xsd:element type="processType" name="process" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="transitionType">
        <xsd:sequence>
            <xsd:element type="xsd:string" name="source"/>
            <xsd:element type="xsd:string" name="target"/>
            <xsd:element type="xsd:string" name="event" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="happy" use="optional"/>
        <xsd:attribute type="xsd:string" name="condition" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="eventType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute type="xsd:string" name="name" use="required"/>
                <xsd:attribute type="xsd:string" name="timeout" use="optional"/>
                <xsd:attribute type="xsd:string" name="onEnter" use="optional"/>
                <xsd:attribute type="xsd:string" name="manual" use="optional"/>
                <xsd:attribute type="xsd:string" name="command" use="optional"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="subprocessesType">
        <xsd:sequence>
            <xsd:element name="process" maxOccurs="unbounded" minOccurs="0">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string" />
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="eventsType">
        <xsd:sequence>
            <xsd:element type="eventType" name="event" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== spryker/spryker-core/Bundles/Braintree/config/Zed/Oms/BraintreeSubProcesses/Refund.xml
<?xml version="1.0"?>
<statemachine
        xmlns="spryker:oms"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="spryker:oms http://static.spryker.com/oms-01.xsd">

    <process name="Refund">
        <states>
            <state name="ready for refund"/>
            <state name="refund succeeded"/>
        </states>

        <transitions>
            <transition condition="Braintree/IsRefundApproved">
                <source>ready for refund</source>
                <target>refund succeeded</target>
                <event>refund payment</event>
            </transition>
        </transitions>

        <events>
            <event name="refund payment" manual="true" onEnter="true" command="Braintree/Refund"/>
        </events>
    </process>
</statemachine>
